[env]
TERM = "xterm-256color"

[font]
  # Normal (roman) font face
  size = 12.0

  [font.normal]
    family = "JetBrainsMono Nerd Font"
    style = "Regular"  # The `style` can be specified to pick a specific face.

  # Bold font face
  [font.bold]
    family = "JetBrainsMono Nerd Font"
    style = "Bold"  # The `style` can be specified to pick a specific face.

  # Italic font face
  [font.italic]
    family = "JetBrainsMono Nerd Font"
    style = "Italic"  # The `style` can be specified to pick a specific face.

  # Point size of the font

  # Offset is the extra space around each character.
  [font.offset]
    x = 0
    y = 0

  # Glyph offset determines the locations of the glyphs within their cells.
  [font.glyph_offset]
    x = 0
    y = 0

# [font.normal]
# family = "MesloLGS NF"

[window]
option_as_alt = 'OnlyLeft'

# [[keyboard.bindings]]
# key = "J"
# mods = "Alt"
# chars = "\\x1bj"
#
# [[keyboard.bindings]]
# key = "K"
# mods = "Alt"
# chars = "\\x1bk"
#
# [[keyboard.bindings]]
# key = "H"
# mods = "Alt"
# chars = "\\x1bh"
#
# [[keyboard.bindings]]
# key = "L"
# mods = "Alt"
# chars = "\\x1bl"
