---
name: cpd
root: ~/Work/omnisource/cpd
windows:
  - root:
      layout: main-horizontal
      panes:
        - ""
        - ""
        - ""
  - node-api:
      root: node-api
      layout: main-horizontal
      panes:
        - ""
        - ""
        - ""
  - react-app:
      root: react-app
      layout: main-horizontal
      panes:
        - ""
        - ""
        - ""
  - claim:
      root: claim-react-app
      layout: main-horizontal
      panes:
        - ""
        - ""
        - ""
  - node-api-background:
      root: node-api
      layout: main-horizontal
      panes:
        - ""
        - ""
        - ""
